# Generated by Django 5.2.17 on 2026-08-27 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('stock_policy', models.CharField(choices=[('tracked', 'Tracked'), ('inquiry_only', 'Inquiry only')], default='tracked', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='catalog.productvariant')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('available_quantity'))), name='inventory_reserved_lte_available')],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('reserved_change', models.IntegerField(default=0)),
                ('reason', models.CharField(choices=[('initial', 'Initial stock'), ('receipt', 'Stock receipt'), ('adjustment', 'Manual adjustment'), ('reservation', 'Reservation'), ('release', 'Reservation release'), ('sale', 'Sale')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_change', 0), ('reserved_change', 0), _negated=True), name='inventory_transaction_has_change')],
            },
        ),
    ]
