# Generated by Django 5.2.17 on 2026-09-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='reason',
            field=models.CharField(choices=[('initial', 'Initial stock'), ('receipt', 'Stock receipt'), ('adjustment', 'Manual adjustment'), ('reservation', 'Reservation'), ('release', 'Reservation release'), ('sale', 'Sale'), ('cancellation', 'Order cancellation')], max_length=20),
        ),
    ]
