# Generated by Django 5.2.17 on 2026-09-01 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('stock_restored', False), ('status', 'cancelled'), _connector='OR'), name='orders_restored_only_when_cancelled'),
        ),
    ]
