# Generated by Django 5.2.17 on 2026-09-02 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_orders_restored_only_when_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, editable=False, max_length=120)),
                ('livemode', models.BooleanField(editable=False)),
                ('processed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('outcome', models.CharField(blank=True, editable=False, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(default='stripe', editable=False, max_length=20)),
                ('idempotency_key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('provider_checkout_session_id', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True)),
                ('provider_payment_intent_id', models.CharField(blank=True, db_index=True, editable=False, max_length=255)),
                ('checkout_url', models.URLField(blank=True, editable=False, max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('currency', models.CharField(default='THB', editable=False, max_length=3)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('open', 'Open'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='creating', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='orders.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payments_amount_non_negative'), models.UniqueConstraint(condition=models.Q(('status__in', ('creating', 'open'))), fields=('order',), name='payments_one_open_attempt_per_order')],
            },
        ),
    ]
